# Generated by Django 3.0.3 on 2022-01-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='DISLIKES',
        ),
        migrations.RemoveField(
            model_name='review',
            name='LIKES',
        ),
    ]
